require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ExternalSpsController do

  # This should return the minimal set of attributes required to create a valid
  # ExternalSp. As you add validations to ExternalSp, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExternalSpsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all external_sps as @external_sps" do
      external_sp = ExternalSp.create! valid_attributes
      get :index, {}, valid_session
      assigns(:external_sps).should eq([external_sp])
    end
  end

  describe "GET show" do
    it "assigns the requested external_sp as @external_sp" do
      external_sp = ExternalSp.create! valid_attributes
      get :show, {:id => external_sp.to_param}, valid_session
      assigns(:external_sp).should eq(external_sp)
    end
  end

  describe "GET new" do
    it "assigns a new external_sp as @external_sp" do
      get :new, {}, valid_session
      assigns(:external_sp).should be_a_new(ExternalSp)
    end
  end

  describe "GET edit" do
    it "assigns the requested external_sp as @external_sp" do
      external_sp = ExternalSp.create! valid_attributes
      get :edit, {:id => external_sp.to_param}, valid_session
      assigns(:external_sp).should eq(external_sp)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ExternalSp" do
        expect {
          post :create, {:external_sp => valid_attributes}, valid_session
        }.to change(ExternalSp, :count).by(1)
      end

      it "assigns a newly created external_sp as @external_sp" do
        post :create, {:external_sp => valid_attributes}, valid_session
        assigns(:external_sp).should be_a(ExternalSp)
        assigns(:external_sp).should be_persisted
      end

      it "redirects to the created external_sp" do
        post :create, {:external_sp => valid_attributes}, valid_session
        response.should redirect_to(ExternalSp.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved external_sp as @external_sp" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExternalSp.any_instance.stub(:save).and_return(false)
        post :create, {:external_sp => {  }}, valid_session
        assigns(:external_sp).should be_a_new(ExternalSp)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExternalSp.any_instance.stub(:save).and_return(false)
        post :create, {:external_sp => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested external_sp" do
        external_sp = ExternalSp.create! valid_attributes
        # Assuming there are no other external_sps in the database, this
        # specifies that the ExternalSp created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ExternalSp.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => external_sp.to_param, :external_sp => { "these" => "params" }}, valid_session
      end

      it "assigns the requested external_sp as @external_sp" do
        external_sp = ExternalSp.create! valid_attributes
        put :update, {:id => external_sp.to_param, :external_sp => valid_attributes}, valid_session
        assigns(:external_sp).should eq(external_sp)
      end

      it "redirects to the external_sp" do
        external_sp = ExternalSp.create! valid_attributes
        put :update, {:id => external_sp.to_param, :external_sp => valid_attributes}, valid_session
        response.should redirect_to(external_sp)
      end
    end

    describe "with invalid params" do
      it "assigns the external_sp as @external_sp" do
        external_sp = ExternalSp.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExternalSp.any_instance.stub(:save).and_return(false)
        put :update, {:id => external_sp.to_param, :external_sp => {  }}, valid_session
        assigns(:external_sp).should eq(external_sp)
      end

      it "re-renders the 'edit' template" do
        external_sp = ExternalSp.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExternalSp.any_instance.stub(:save).and_return(false)
        put :update, {:id => external_sp.to_param, :external_sp => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested external_sp" do
      external_sp = ExternalSp.create! valid_attributes
      expect {
        delete :destroy, {:id => external_sp.to_param}, valid_session
      }.to change(ExternalSp, :count).by(-1)
    end

    it "redirects to the external_sps list" do
      external_sp = ExternalSp.create! valid_attributes
      delete :destroy, {:id => external_sp.to_param}, valid_session
      response.should redirect_to(external_sps_url)
    end
  end

end
